lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_identity_field: getEmail

    blocklist_token:
        enabled: true
        cache: cache.app

    api_platform:
        check_path: /api/login
        username_path: email
        password_path: password

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization


